using System.Security.Cryptography;

namespace EchoRelay.Core.Utils
{
    /// <summary>
    /// A <see cref="Guid"/> generator, backed by a cryptographically secure random number generator (CSRNG).
    /// </summary>
    public class SecureGuidGenerator
    {
        /// <summary>
        /// Generates a new <see cref="Guid"/> using a cryptographically secure RNG.
        /// </summary>
        /// <returns>Returns the newly generated <see cref="Guid"/>.</returns>
        public static Guid Generate()
        {
            // Create a new GUID from the cryptographically secure random generated bytes.
            return new Guid(RandomNumberGenerator.GetBytes(16));
        }
    }
}
